# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default='City Pleaseee.....', max_length=15),
        ),
        migrations.AddField(
            model_name='userdata',
            name='zipcode',
            field=models.CharField(default='Zipcode?', max_length=6),
        ),
    ]
