# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidata',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='maidata',
            name='language',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='maidata',
            name='worktype',
            field=models.CharField(choices=[('FULLT', 'FULL TIME'), ('PARTT', 'PART TIME')], default='FULLT', max_length=1),
        ),
    ]
