# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_auto_20180211_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maidata',
            name='worktype',
        ),
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='language',
            field=models.CharField(choices=[('HINDI', 'Hindi'), ('MARATHI', 'Marathi')], default='MARATHI', max_length=8),
        ),
        migrations.AddField(
            model_name='userdata',
            name='worktype',
            field=models.CharField(choices=[('FULLT', 'FULL TIME'), ('PARTT', 'PART TIME')], default='FULLT', max_length=5),
        ),
    ]
