# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_auto_20180211_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='code',
            field=models.CharField(default='Unique Maid ID', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.TextField(default='Address'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='worktype',
            field=models.CharField(choices=[('Replacement', 'REPLACEMENT'), ('New Subscription', 'NEW SUBSCRIPTION')], default='Replacement', max_length=15),
        ),
    ]
